package org.openui5;

public enum Resource {
	RUNTIME_DOWNLOAD,
	MOBILE_DOWNLOAD,
	SDK_DOWNLOAD,
	GITHUB_PAGE,
	BLOG_PAGE,
	REFERENCES_PAGE,
	FEATURES_PAGE,
	GETSTARTED_PAGE,
	DEMOKIT_PAGE,
	CORE, 
	VERSIONED_CORE
}
