import globals from "globals";
import { defineConfig } from "eslint/config";
import jsdoc from "eslint-plugin-jsdoc";
import sapUiCore from "./src/sap.ui.core/eslint.config.mjs";
import sapUiDt from "./src/sap.ui.dt/eslint.config.mjs";
import sapUiFl from "./src/sap.ui.fl/eslint.config.mjs";
import sapUiMdc from "./src/sap.ui.mdc/eslint.config.mjs";
import sapUiRta from "./src/sap.ui.rta/eslint.config.mjs";
import sapUiTable from "./src/sap.ui.table/eslint.config.mjs";

export default defineConfig([
  {
    name: "openui5-ignores",
    ignores: [
      "**/dist",
      "**/target",
      "**/node_modules",
      // library specific excludes - need to be consistent with the library-local .eslintignore files
      "src/sap.ui.core/ui5lint.config.js",
      "src/sap.ui.core/src/sap/ui/thirdparty",
      "src/sap.ui.core/src/sap/base/util/restricted/_",
      "src/sap.ui.core/test/sap/ui/core/qunit/thirdparty",
      "src/sap.m/src/sap/m/_thirdparty",
      "src/sap.m/test/sap/m/demokit/cart/webapp/Component.js",
      "src/sap.m/test/sap/m/demokit/master-detail/webapp/Component.js",
      "src/sap.m/test/sap/m/demokit/master-detail/webapp/controller/BaseController.js",
      "src/sap.m/test/sap/m/demokit/master-detail/webapp/controller/Master.controller.js",
      "src/sap.m/test/sap/m/demokit/master-detail/webapp/test/testsuite.qunit.js",
      "src/sap.m/test/sap/m/demokit/worklist/webapp/Component.js",
      "src/sap.m/test/sap/m/demokit/worklist/webapp/controller/Worklist.controller.js",
      "src/sap.m/test/sap/m/demokit/worklist/webapp/test/testsuite.qunit.js",
      "src/sap.m/test/sap/m/qunit/_thirdparty",
      "src/sap.ui.documentation/src/sap/ui/documentation/sdk/model/data/guide",
      "src/sap.ui.documentation/src/sap/ui/documentation/sdk/thirdparty",
      "src/sap.ui.codeeditor/src/sap/ui/codeeditor/js",
      "src/sap.ui.fl/test/sap/ui/fl/qunit/testResources/TestChangeHandlersBROKEN.flexibility.js",
      "src/sap.ui.fl/test/sap/ui/fl/testApps/controlPersonalizationAPI/test/testsuite.qunit.js",
      "src/sap.ui.integration/src/sap/ui/integration/thirdparty",
      "src/sap.ui.integration/src/sap/ui/integration/designtime/thirdparty",
      "src/sap.ui.webc.main/src/sap/ui/webc/main/thirdparty",
      "src/sap.ui.webc.common/src/sap/ui/webc/common/thirdparty",
      "src/sap.ui.webc.fiori/src/sap/ui/webc/fiori/thirdparty",
      "src/sap.ui.webc.fiori/src/sap/ui/webc/fiori/lib",
      "src/sap.ui.support/src/sap/ui/support/js",
    ],
  },
  {
    name: "openui5",
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "script",
      globals: {
        ...globals.browser,
        ...globals.jquery,
        sap: "readonly",
      },
    },
    plugins: {
      jsdoc,
    },
    rules: {
      // Possible Errors
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-console": "error",
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-dupe-args": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty-character-class": "error",
      "no-empty": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": ["error", { enforceForLogicalOperands: true }],
      "no-extra-parens": ["error", "functions"],
      "no-extra-semi": "error",
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-inner-declarations": ["error", "functions"],
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": ["error", { skipStrings: false }],
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-obj-calls": "error",
      "no-promise-executor-return": "error",
      "no-regex-spaces": "error",
      "no-setter-return": "error",
      "no-sparse-arrays": "error",
      "no-unreachable-loop": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": ["error", { enforceForOrderingRelations: true }],
      "no-unsafe-optional-chaining": [
        "error",
        { disallowArithmeticOperators: true },
      ],
      "no-useless-backreference": "error",
      "require-atomic-updates": ["error", { allowProperties: true }],
      "use-isnan": "error",
      "valid-typeof": ["error", { requireStringLiterals: true }],

      // Best Practices
      "accessor-pairs": "error",
      "block-scoped-var": "warn",
      "consistent-return": "warn",
      curly: ["error", "all"],
      "default-case-last": "error",
      "default-case": "warn",
      "default-param-last": "error",
      "grouped-accessor-pairs": "error",
      "no-alert": "error",
      "no-caller": "error",
      "no-case-declarations": "error",
      "no-constant-binary-expression": "error",
      "no-constructor-return": "error",
      "no-div-regex": "error",
      "no-empty-pattern": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-fallthrough": "error",
      "no-floating-decimal": "error",
      "no-global-assign": "error",
      "no-implicit-globals": ["error", { lexicalBindings: true }],
      "no-implied-eval": "error",
      "no-iterator": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-loop-func": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-new": "warn",
      "no-nonoctal-decimal-escape": "error",
      "no-octal-escape": "error",
      "no-octal": "error",
      "no-proto": "error",
      "no-redeclare": "warn",
      "no-return-assign": ["error", "always"],
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-unmodified-loop-condition": "error",
      "no-unused-expressions": "warn",
      "no-unused-labels": "error",
      "no-useless-catch": "error",
      "no-void": "error",
      "no-warning-comments": ["warn", { location: "anywhere" }],
      "no-with": "error",
      "prefer-object-has-own": "error",
      radix: ["error", "as-needed"],
      "require-await": "error",
      "wrap-iife": ["error", "any"],
      yoda: "error",

      // Strict Mode
      strict: ["error", "function"],

      // Variables
      "no-delete-var": "error",
      "no-label-var": "error",
      "no-restricted-globals": [
        "warn",
        "closed",
        "defaultStatus",
        "frames",
        "history",
        "innerHeight",
        "innerWidth",
        "length",
        "location",
        "menubar",
        "name",
        "navigator",
        "opener",
        "pageXOffset",
        "pageYOffset",
        "parent",
        "personalbar",
        "scrollbars",
        "status",
        "statusbar",
        "toolbar",
        "blur",
        "close",
        "find",
        "focus",
        "moveBy",
        "moveTo",
        "open",
        "print",
        "resizeBy",
        "resizeTo",
        "scroll",
        "scrollBy",
        "scrollTo",
        "stop",
        "onload",
      ],
      "no-shadow-restricted-names": "error",
      "no-undef-init": "error",
      "no-undef": "error",
      "no-unused-vars": [
        "error",
        { vars: "all", args: "none", caughtErrors: "none" },
      ],
      "no-use-before-define": ["warn", "nofunc"],

      // Stylistic Issues
      "brace-style": ["error", "1tbs", { allowSingleLine: true }],
      camelcase: "warn",
      "comma-dangle": ["error", "never"],
      "consistent-this": ["warn", "that"],
      "func-call-spacing": ["error", "never"],
      "keyword-spacing": ["error", { after: true }],
      "linebreak-style": "error",
      "max-nested-callbacks": ["warn", 3],
      "new-cap": "warn",
      "new-parens": "error",
      "no-array-constructor": "error",
      "no-lonely-if": "warn",
      "no-mixed-spaces-and-tabs": ["error", "smart-tabs"],
      "no-nested-ternary": "error",
      "no-new-object": "error",
      "no-trailing-spaces": "error",
      "quote-props": [
        "error",
        "as-needed",
        { keywords: true, unnecessary: false },
      ],
      "semi-spacing": ["warn", { before: false, after: true }],
      "semi-style": ["error", "last"],
      semi: "error",
      "space-infix-ops": "error",
      "space-unary-ops": ["error", { words: true, nonwords: false }],
      "template-tag-spacing": ["error", "never"],
      "unicode-bom": ["error", "never"],

      // ECMAScript 6
      "arrow-parens": "error",
      "arrow-spacing": "error",
      "constructor-super": "error",
      "generator-star-spacing": "error",
      "no-class-assign": "error",
      "no-confusing-arrow": "error",
      "no-const-assign": "error",
      "no-dupe-class-members": "error",
      "no-duplicate-imports": "error",
      "no-empty-static-block": "error",
      "no-new-native-nonconstructor": "error",
      "no-new-symbol": "error",
      "no-this-before-super": "error",
      "no-unused-private-class-members": "error",
      "no-useless-computed-key": "error",
      "no-useless-rename": "error",
      "prefer-const": "error",
      "prefer-numeric-literals": "error",
      "require-yield": "error",
      "rest-spread-spacing": ["error", "never"],
      "symbol-description": "error",
      "yield-star-spacing": "error",

      // Deprecated
      "jsdoc/require-returns": ["warn"],

      // Rules that have been decided to not activate
      "arrow-body-style": "off",
      "class-methods-use-this": "off",
      "lines-between-class-members": "off",
      "logical-assignment-operators": "off",
      "max-classes-per-file": "off",
      "no-await-in-loop": "off",
      "no-multi-str": "off", // Enable when template literals (ES6 syntax) can be used
      "no-restricted-exports": "off",
      "no-restricted-imports": "off",
      "no-restricted-properties": "off",
      "no-return-await": "off",
      "no-useless-constructor": "error", // JSDoc does not count as non-useless content
      "sort-imports": "off",
      "template-curly-spacing": "off",
    },
  },
  {
    name: "openui5-no-jquery",
    files: [
      "src/sap.f/**/*.js",
      "src/sap.m/**/*.js",
      "src/sap.tnt/**/*.js",
      "src/sap.ui.documentation/**/*.js",
      "src/sap.ui.integration/**/*.js",
      "src/sap.ui.layout/**/*.js",
      "src/sap.ui.mdc/src/**/*.js",
      "src/sap.ui.mdc/test/sap/ui/mdc/demokit/**/*.js",
      "src/sap.ui.mdc/test/sap/ui/mdc/integration/**/*.js",
      "src/sap.ui.mdc/test/sap/ui/mdc/qunit/**/*.js",
      "src/sap.ui.table/**/*.js",
      "src/sap.ui.unified/src/**/*.js",
      "src/sap.ui.unified/test/sap/ui/unified/demokit/**/*.js",
      "src/sap.ui.unified/test/sap/ui/unified/sample/**/*.js",
      "src/sap.ui.unified/test/sap/ui/unified/qunit/**/*.js",
      "src/sap.uxap/**/*.js",
    ],
    languageOptions: {
      globals: {
        jQuery: "off",
      },
    },
  },
  {
    name: "openui5-cjs",
    files: [
      "src/**/*.spec.js",
      "src/sap.ui.integration/test/sap/ui/integration/visual/cardVisualTestUtils.js",
    ],
    languageOptions: {
      sourceType: "commonjs",
      globals: {
        describe: "readonly",
        it: "readonly",
        element: "readonly",
        by: "readonly",
        takeScreenshot: "readonly",
        expect: "readonly",
      },
    },
  },
  {
    name: "openui5-libs",
    extends: [sapUiCore, sapUiDt, sapUiFl, sapUiMdc, sapUiRta, sapUiTable],
  },
]);
