sap.ui.define([
    "./_BindingPath",
    "./_ControlSelectorGenerator",
    "./_DropdownItem",
    "./_GlobalID",
    "./_LabelFor",
    "./_Properties",
    "./_Selector",
    "./_TableRowItem",
    "./_ViewID"
]);
